"""
    cmt_parser.jl

# Description
This script is used to develop the parsing of CMT edge attribute data.
This script is tied to experiment `2_cmt` and requires data generated by those Python scripts.

# Authors
- Sasha Petrenko <petrenkos@mst.edu>
"""

# -----------------------------------------------------------------------------
# PREAMBLE
# -----------------------------------------------------------------------------

using Revise
using OAR

# -----------------------------------------------------------------------------
# VARIABLES
# -----------------------------------------------------------------------------

# Location of the edge attributes file, formatted for Lerch parsing
edge_file = OAR.results_dir("2_cmt", "edge_attributes_lerche.txt")

# -----------------------------------------------------------------------------
# PARSE ARGS
# -----------------------------------------------------------------------------

# Parse the arguments provided to this script
pargs = OAR.exp_parse(
    "0_init/cmt_parser.jl: parsing the CMT edge attirbutes dataset."
)

# -----------------------------------------------------------------------------
# EXPERIMENT
# -----------------------------------------------------------------------------

# Construct the CMT parser
cmt_parser = OAR.get_cmt_parser()

# Set some sample text as the input statement
text = raw"\"Periaxin\" \"is_a\" \"protein\""

# Parse the statement
k = OAR.run_parser(cmt_parser, text)

# Initialize the statements vector
statements = Vector{OAR.CMTStatement}()
# Open the edge attributes file and parse
open(edge_file) do f
    line = 0
    while ! eof(f)
        # Read the line from the file
        s = readline(f)
        line += 1
        # Parse the line into a structured statement
        k = OAR.run_parser(cmt_parser, s)
        push!(statements, k)
        # @info "$line : $k"
    end
end

@info statements
